---
# Build F5 VMs
- hosts: localhost
  connection: local
  gather_facts: true
  vars_files:
    - ../vars/Vault/vault.yml
    - ../vars/HZN-Lab/deployment.yml
  roles:
    - roles/vSphere-Roles/create_dyn_group_f5_vms

- hosts: dynamic_f5_vms
  connection: local
  gather_facts: false
  vars_files:
    - ../vars/Vault/vault.yml
    - ../vars/HZN-Lab/deployment.yml
  roles:
    - roles/F5-Roles/wait_for_bigip_startup
    - roles/F5-Roles/as3_configure