---
- name: LINKLIGHT AS3
  hosts: lb
  connection: local
  gather_facts: false

  tasks:
    - name: Set Provider
      set_fact:
        provider:
            server: "{{  ansible_host  }}"
            user: "{{ f5_user }}"
            password: "{{ f5_pass }}"
            server_port: "{{  f5_admin_port  }}"
            validate_certs: "no"

    - name: Get Failover State - Module
      bigip_command:
        commands: show sys failover
        provider: "{{ provider }}"
      register: f5_info

    - name: DELETE AS3
      ansible.builtin.uri:
        url: "https://{{ ansible_host }}:{{f5_admin_port}}/mgmt/shared/appsvcs/declare/Customer-Tenant"
        method: DELETE
        status_code: 200
        timeout: 300
        body_format: json
        force_basic_auth: true
        user: "{{ f5_user }}"
        password: "{{ f5_pass }}"
        validate_certs: false
      delegate_to: localhost
      when: 
      - f5_info.stdout[0].split()[1] |lower == "active"
      - tenant_info_var.tenant_name in inventory_hostname
      register: as3_result
