---
# tasks file for Create-VM

 - name: Shutdown Guest OS Master Templates
   include: shutdown_guest_os.yml
   with_items: "{{f5_ova_builds}}"
   loop_control:
     loop_var: ova_builds_var

 - name: Snapshot Master Templates
   include: take_snap.yml
   with_items: "{{f5_ova_builds}}"
   loop_control:
     loop_var: ova_builds_var